### ISSUE TITLE
Algorithm test performance metric

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#100]
A more structured discussion (with documentation) needs to be made about methods to calculate the algorithm performance.

Currently, the metric is:
` error = sum( supply_timeseries - demand_timeseries)`

**Comment by jbae11** [comment]
possible candidates are:
`r-squared method`
`number of undersupplies`
`weighted error` : absolute error + harsher penalty for undersupplies
```
ex)
error = supply_timeseries - demand_timeseries
bad_score = 0
for i in error:
    if i < 0:
        # alpha is some coefficient for `harshness' of penalty
        bad_score += alpha * i
    else:
        bad_score += i
```

**Comment by gwenchee** [comment]
perhaps: Chi Square Goodness of Fit Test

**Comment by gwenchee** [comment]
closed with https://github.com/ergs/d3ploy/pull/124
