### ISSUE TITLE
We need typsystem.MapStringPairStringMapStringString

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#102]
The desired input structure for commodity and facility definition is:
```
<commodity>
    <val>power</val>
        <item>
            <facility_name>LWR</facility_name>
            <info>
                <cap>1000</cap>
                <pref>100-3*t</pref>
            </info>
        </item>
        <item>
            <facility_name>sfr</facility_name>
            <info>
                <cap>600</cap>
                <pref>3*t</pref>
            </info>
        </item>
</commodity>

**Comment by gwenchee** [comment]
We can probably do a default value for the pref map in this situation @FlanFlanagan . By having some sort of catch in the code that says that if the map pref doesn't exist, it just automatically gives the facility a pref of 1.

**Comment by FlanFlanagan** [comment]
I don't think defaults work like that. You need a default for the whole variable, not a specific part of the variable. So you would have to fill out pref no matter what. Otherwise it will fail the XML schema validation.

**Comment by robfairh** [comment]
Do we still want this?
@gwenchee

**Comment by gwenchee** [comment]
Since multi level maps do not work Cyclus python archetypes (https://github.com/cyclus/cyclus/issues/1500), we instead implemented https://github.com/arfc/d3ploy/issues/212. This issue can be closed.
