### ISSUE TITLE
Unit test for solvers

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#107]
We need unit tests for all solvers,

**Comment by gwenchee** [comment]
unit tests for functions in `NO_solvers.py`, `DO_solvers.py` and `ML_solvers.py`

**Comment by jbae11** [comment]
@FlanFlanagan Can you enlighten me how these tests would look like?

My intuition is that it would be to assert an analytical solution to the returned value of the function, but I'm not quite sure how to implement that in code. This is what I currently have:

https://github.com/jbae11/d3ploy/blob/solver_tests/tests/unit_tests/no_tests.py

**Comment by FlanFlanagan** [comment]
If this is what we discussed today, then I don't think we need this. 

Specifically, we should not be testing if someone else code works. So no need to check if the ARMA function is working correctly, just that we implement it correctly. So unit testing that it actually deploys facilities should be enough.

**Comment by jbae11** [comment]
sounds good!
