### ISSUE TITLE
expand performance testing 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#108]
expand for more scenarios 
- transitions

**Comment by robfairh** [comment]
Should there be more demonstration cases?
Or this is address why the transition scenarios eg01-eg23/eg24/eg29/eg30?
@gwenchee

**Comment by gwenchee** [comment]
Yeah this is aimed at the transition scenarios, so if we have issues for each of the specific transition scenarios, then this issue can be closed? @robfairh

**Comment by robfairh** [comment]
yes, #177, #178, #179, #180 address the same issue.
