### ISSUE TITLE
Decommission in NO archetype. 

### ISSUE THREAD

**Issue by FlanFlanagan** [arfc/d3ploy#11]
Remember to add decommissioning behavior to region NO archetype.

**Comment by gwenchee** [comment]
User input: Supply - Demand percentage difference for when to start decommissioning facilities  
Decommissioning logic: 
If Supply - Demand percentage difference for when to start decommissioning facilities is at percentage that user defined and the decommissioning of the smallest facility does not go under 5% (?) of the difference, then the smallest and oldest facility is decommissioned.

**Comment by gwenchee** [comment]
The criteria for decommissioning a facility could be: if supply is larger than demand for that commodity for capacity of smallest facility in user-defined amount of time steps, the smallest facility is decommissioned

**Comment by katyhuff** [comment]
Conditions should come from the user:
- oversupply threshold for each commodity (default: smallest facility capacity)
- time steps of oversupply tolerated for each commodity (default: 1 year)

Logic: smallest facility producing the commodity is decommissioned if oversupply is greater than facility capacity.

**Comment by gwenchee** [comment]
The issue of what happens to a commodity that is being collected for use in a transition, can be worked around by not applying decommissioning to commodities that are deemed a " constraint commodity"

**Comment by FlanFlanagan** [comment]
#230 should tackle this issue.

**Comment by robfairh** [comment]
closed by #230
