### ISSUE TITLE
add SO algorithms to performance testing python script

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#111]
This can be closed when: unit tests have been implemented to check performance of the SO algorithms.

**Comment by katyhuff** [comment]
ARIMA method should be added to performance structure.

**Comment by katyhuff** [comment]
@FlanFlanagan What's the status of this?

**Comment by FlanFlanagan** [comment]
PR #291 added to address this.

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/d3ploy/pull/291
