### ISSUE TITLE
fill up issues for this milestone 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#112]

**Comment by FlanFlanagan** [comment]
This is in reference to milestone 4. 

Journal article about how Rickshaw operates.

**Comment by FlanFlanagan** [comment]
I've started this paper based on operation of Rickshaw. 

Specifically focusing on using the transition guessing behavior of rickshaw to pick out the right transition deployment. I'm not sure this will be full journal article worthy, but it will fit in well with the final report of this NEUP as an appendix.
