### ISSUE TITLE
output results from algorithm performance tests to a different format

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#125]
it is currently output into a txt file 
perhaps 
- csv 
- hdf5 
- sqlite

**Comment by jbae11** [comment]
a way to turn it into a csv is using pandas, after putting all the metrics into an organized dictionary:
```
import pandas as pd
my_dict = {'residuals': {'poly': 11, 'fft':13, 'winter':10},
           'chi2': {'poly':2, 'fft':1, 'winter':3},
           'fail': {'poly':0, 'fft': 3, 'winter': 4}}
df = pd.DataFrame(my_dict)
df.to_csv('text.csv')
```
this returns:
```
,residuals,chi2,fail
fft,13,1,3
poly,11,2,0
winter,10,3,4
```
we do lose the 'best performance' part, though.
if @gwenchee and @FlanFlanagan think this is a good idea, I will implement this

**Comment by gwenchee** [comment]
Would this be implemented within the algorithm_performance_test.py file?

**Comment by jbae11** [comment]
yup

**Comment by jbae11** [comment]
see #137

**Comment by jbae11** [comment]
it is now in csv format
