### ISSUE TITLE
module not found 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#128]
I am running into this issue when installing the develop branch of ergs/d3ploy: `No module found for path libd3ploy.timeseries_inst.so` . This might be due to similar reasons in this other issue: https://github.com/ergs/d3ploy/issues/64

**Comment by FlanFlanagan** [comment]
This is because it is not installing properly. 

One of the files included in the install is not compiling and so the module does not get built.

**Comment by gwenchee** [comment]
Do you know how to fix it? @FlanFlanagan

**Comment by FlanFlanagan** [comment]
Yeah, fix the error in the code. Someone must have merged in some bad code.

**Comment by FlanFlanagan** [comment]
It's probably an import bug, or a missing python package.

**Comment by FlanFlanagan** [comment]
My guess is that you don't have arima installed. 

pip install pyramid-arima

**Comment by gwenchee** [comment]
You are correct. Thanks!
