### ISSUE TITLE
Deterministic solution to d3ploy problem

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#130]
Deterministic solution to d3ploy problem will be implemented using a matrix operation that determines the demand in time step `x` by using the deployment information in the time step `x-1` and based on that deploys facilities in `x` to meet this demand

**Comment by katyhuff** [comment]
@FlanFlanagan : Please point to the place where this has been implemented (commit, pr, ipynb) to close this issue.

**Comment by FlanFlanagan** [comment]
Handled in PR #183
