### ISSUE TITLE
tests very out of date

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#138]
The tests `NO_fleet_unit_tests` and `NO_unit_tests` are very out of date, referencing to past input syntax and functions that do not exist anymore. They should be updated so that the tests succeed.

**Comment by FlanFlanagan** [comment]
this should be done with PR's are made. 

What's the issue with these tests?

**Comment by jbae11** [comment]
the `NO_unit_tests` uses former d3ploy syntax [here](https://github.com/ergs/d3ploy/blob/develop/tests/integration_tests/NO_unit_tests.py#L130)

and `NO_fleet_unit_tests` uses a function that's not in the tester class
