### ISSUE TITLE
continuous integration test test criteria

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#139]
currently the `continuous_integration_test.py` tests:
```
    fuel_demand = cur.execute(
        "select time, sum(value) from timeseriesdemandfreshfuel group by time").fetchall()
    fuel_supply = cur.execute(
        "select time, sum(value) from timeseriessupplyfreshfuel group by time").fetchall()
    power_demand = cur.execute(
        "select time, sum(value) from timeseriespower group by time").fetchall()
    power_supply = cur.execute(
        "select time, sum(value) from timeseriessupplypower group by time").fetchall()
    # Adding up the first time step of each table
    total[calc_methods[x]] = fuel_demand[0][0] + \
        fuel_supply[0][0]+power_demand[0][0]+power_supply[0][0]

---- pass if total is 4
```
which has room for false positives and false negatives because it is adding up the first entry's time values, which can be 1 or 2 or more. If the goal is to check if all the tables have entries on them (or if facilities have been deployed), maybe it's better to check the `agententry` table

**Comment by jbae11** [comment]
@gwenchee thoughts?

**Comment by gwenchee** [comment]
Ya that makes sense

**Comment by gwenchee** [comment]
i can fix it now

**Comment by jbae11** [comment]
in PR #140 
commit [7416bd3] (https://github.com/ergs/d3ploy/pull/140/commits/7416bd31a671bd1ef8ace72c16bb7bda213cc1cf) changes the test criteria to see if there's a facility (reactor, source) deployed by querying the `agententry` table
