### ISSUE TITLE
driving commodity in SupplyInst? 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#145]
Should the `supply_demand_driven_deployment_inst.py` institution have the notion of driving commodity or not? 

I think it shouldn't. But, what do you guys think? @FlanFlanagan @jbae11 

`timeseries_inst.py ` has a notion of demand and supply. The input for the commodity variable is `POWER_reactor_capacity` where the supply of that facility is the driving commodity. 

Whereas, I implemented `supply_driven_deployment_inst.py` to have a notion of supply and capacity. So, it would not make sense to have the capacity being a driving commodity?

**Comment by FlanFlanagan** [comment]
That's a good question, I'm not sure if we need the driving commodity for this institution. I'm trying to think of a situation in which a demand for capacity is the driving commodity of a simulation. 

I'm not sure we need a driving commodity for this, but I'm also not sure we gain anything by taking it away. Remember all this change needs to do is reverse where the supply and demand are recorded, so it just changes the two functions used to listen to the recordtimeseries calls.

**Comment by gwenchee** [comment]
True. I think that leaving it in might be a little confusing because a user would still need to input a driving commodity to this new institution despite it not really being used?

**Comment by jbae11** [comment]
maybe we talked about this but why have a separate institution prototype for this? I do understand that the input parameters get rather large but wouldn't it be easier for the user to have the entire fuel cycle definition (facilities involved in the fuel cycle) in one institution?

**Comment by gwenchee** [comment]
We could do that. But you would basically need to copy paste various sections of the code and label it reverse_commodities. So it might be cleaner to just have it as two different institutions.

**Comment by FlanFlanagan** [comment]
It's really not that hard to have two different institutions. I still think they should be separate institutions.  

I think you can safely remove it for now Gwen, or make it a default of blank.

**Comment by jbae11** [comment]
can't it be as simple as multiplying the `diff` variable by negative one? But sure i think two different institutions can work too

**Comment by gwenchee** [comment]
The decision was made during the DDCA call this week. We decided to have 2 separate institutions for front and back end of the fuel cycle and get rid of the notion of `demand eq` and `driving_commod` in the `supply_driven_deployment_inst `

closed with https://github.com/ergs/d3ploy/pull/144
