### ISSUE TITLE
record timeseries with preference values for better implementation

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#156]
If an archetype has multiple demand commodities,
the decision for which commodity to record is done inside the archetype.

However, it  may be better if the preference was recorded in the `timeseries-` tables so that `timeseries_inst` can make its own decisions as to which commodity it is going to 'pursue'. 

For example, if a Cycamore::Reactor has two in commods, `uox` and `mox`, and if `mox` has a higher preference, it will never demand `uox`, and the supply chain will not start, since `mox` requires spent uox.

A fix would be to have a way for `timeseries_inst` to demand `mox` first and then change to `uox` after figuring out that there is no supply of `mox` (timeseriessupplymox is zero for x duration) - i.e. for timestep 1 and 2 it will demand `mox`, but after reading that timeseriessupplymox is zero for 2 durations, it will demand `uox` instead.

Obviously there are concerns of:
1. delayed deployment
2. larger output data size

but I think this is a good way moving forward with modeling transition scenarios.

**Comment by FlanFlanagan** [comment]
So for your example, if the reactor always chooses mox fuel and mox reactors require UOX to start them up, there will be a demand for UOX just later on down the line. 

If the system is set up right it should take care of itself, but we can talk about it more tomorrow.

**Comment by jbae11** [comment]
I think the problem is that demand for spent uox doesnt necessarily lead to a supply in uox, since the reactors deployed to supply spentuox will be demanding mox.

**Comment by FlanFlanagan** [comment]
That seems like the user setting up a bad scenario. I'm not sure we can solve that problem with code. Or rather, I'm not sure we should.

**Comment by jbae11** [comment]
After discussion in the d3ploy google hangout, we decided that this capability is not necessary.
