### ISSUE TITLE
update capacity in commodity_dict

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#163]
The user doesn't necessarily know what the mass capacity of a prototype is, or sometimes the capacity changes (e.g. enrichment). d3ploy should update the user-defined capacity to the supply recorded by the archetype.

But this is where it gets tricky:
Should we update the capacity to:
1. the most recent supply recorded by the prototype?
2. the average of the supply recorded by the prototype?

Also, what if two prototypes produce the same commodity? Do we have the means to separate the supply provided by one prototype from another?

**Comment by katyhuff** [comment]
We never want 2. Closing.
