### ISSUE TITLE
Threading.py error 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#17]
Threading error:
`Exception ignored in: <module 'threading' from '/home/gwenchee/anaconda3/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/home/gwenchee/anaconda3/lib/python3.6/threading.py", line 1292, in _shutdown
    assert tlock.locked()
SystemError: <built-in method locked of _thread.lock object at 0x7fb09f34d6c0> returned a result with an error set
`
This error appears when time series listeners line is used in `no_inst.py`
`lib.TIME_SERIES_LISTENERS[~].append(~)`

**Comment by katyhuff** [comment]
@FlanFlanagan I'm looking at this now and ...  this seems to be the most important issue of all of these, since it blocks the ability for you to PR your FlanFlanagan/d3ploy (region) branch into ergs/d3ploy (master).

Is that right? What can I/we do to help figure this issue out?

**Comment by FlanFlanagan** [comment]
closed with #26
