### ISSUE TITLE
add additional scenario for back deployment with cycle time = 18, refuel time = 1

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#172]

**Comment by robfairh** [comment]
@gwenchee 
Is this still necessary?

**Comment by gwenchee** [comment]
Yup I’m working on implementing this

**Comment by robfairh** [comment]
What formatting are you using for the demonstration cases?

**Comment by gwenchee** [comment]
We can discuss this IRL?

**Comment by gwenchee** [comment]
A simple version of this is shown here: https://github.com/arfc/d3ploy/blob/master/tests/performance_tests/algorithm_performance_tests_backdeployment.py .
