### ISSUE TITLE
enrichment plot is giving small values 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#175]
The plot generated by `tests/performance_tests/algorithm_performance_tests_transitionscenario.py` https://github.com/ergs/d3ploy/pull/174/files, gives a really small value at time = 0. This issue can be closed when this is fixed
![transitionscenario_1_input_sourceout](https://user-images.githubusercontent.com/29397884/50648823-d4dc2980-0f41-11e9-9f79-ac4cfa249a1b.png)

**Comment by robfairh** [comment]
timeseriesdemandsourceout:

![screenshot from 2019-02-14 12-00-34](https://user-images.githubusercontent.com/43791150/52807070-2bb04500-3050-11e9-828b-efa0a001650e.png)

At timestep 1,2, etc some enrichment facilities demand 1.72476340700596e-316 ...

**Comment by robfairh** [comment]
If the inital_feed for the enrichment facility is 0 we get those values. In my input file I changed the initial feed to 1e10 and those values are gone.

![input23sourceout](https://user-images.githubusercontent.com/43791150/52808140-ce69c300-3052-11e9-9cd8-abcf31710928.png)

Now, why does that happen? Why an initial feed of 0 kg of Natural Uranium to the enrichment facility produces a demand of very small amount of Natural Uranium? Is this a bug in the archetype?
Should this open a new issue? @gwenchee 

Can we get timeseriesdemandsourceout for the same input that doesn't use d3ploy?
@FlanFlanagan any thoughts?

**Comment by gwenchee** [comment]
We can just make sure to keep the initial feed at a finite amount so that this error doesn't occur? @robfairh

**Comment by katyhuff** [comment]
Probably best to look closely at https://github.com/cyclus/cycamore/blob/master/src/enrichment.cc to figure out what's happening in the demand.

start here:  https://github.com/cyclus/cycamore/blob/master/src/enrichment.cc#L341

You can see that it requests the *max* between 0.0 and inventory.capacity() - inventory.quantity()).. so if inventory capacity is anything but zero... it seems it would make a request no matter what.. 

This genenerally makes sense, in the context of the way cyclus usually works. The enrichment facility, if it's running, should seek out natural uranium and start enriching it to the best of its ability, immediately. Of course, this perhaps doesn't work well with the way d3ploy works. In the context of d3ploy, and the way you've designed this problem, then it seems you're expecting the enrichment facility to only enrich uranium if some other facility requests enriched uranium... if that's the case then there will need to be an if/then comparison with the requests coming into the facility...

**Comment by robfairh** [comment]
@gwenchee if the initial feed is different to 0 then this doesn't happen.
@katyhuff I looked at it briefly and it exceeds a lot my current knowledge of cycamore. I will look at it in detail and try to find a bug.

Anyway, I re run the input without d3ploy and the demand at t=0 is in that order of magnitude. The initial feed is again 0. (So, there is probably a bug ...)
![screenshot from 2019-02-14 17-01-54](https://user-images.githubusercontent.com/43791150/52823355-3f70a100-307a-11e9-8f1b-98c0c114d9e0.png)

**Comment by katyhuff** [comment]
@robfairh Right -- I described the reason and solution above. Repeated below:

start here: https://github.com/cyclus/cycamore/blob/master/src/enrichment.cc#L341

You can see that it requests the _max_ between 0.0 and inventory.capacity() - inventory.quantity()).. so if inventory capacity is anything but zero... it seems it would make a request no matter what..

This genenerally makes sense, in the context of the way cyclus usually works. The enrichment facility, if it's running, should seek out natural uranium and start enriching it to the best of its ability, immediately. Of course, this perhaps doesn't work well with the way d3ploy works. In the context of d3ploy, and the way you've designed this problem, then it seems you're expecting the enrichment facility to only enrich uranium if some other facility requests enriched uranium... if that's the case then there will need to be an if/then comparison with the requests coming into the facility...

**Comment by robfairh** [comment]
Okay, it makes sense.
Apparently, it does the same thing even though it has an initial feed ...

**Comment by robfairh** [comment]
The demand of sourceout is usually very small for timestep 0. As we are plotting in log scale for the axis y, we get this 10^-200 values. Going back to linear scale will solve the issue.

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/d3ploy/pull/201
