### ISSUE TITLE
mixer and separations change throughput

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#176]
For the separations/mixer facilities, we should use throughput that match real reprocessing plants

**Comment by FlanFlanagan** [comment]
We should use @gtw2 's PyRE instead of mixer and separations

**Comment by robfairh** [comment]
This issue should be in https://github.com/arfc/transition-scenarios instead of here.
This PR https://github.com/arfc/transition-scenarios/pull/107 uses more realistic throughput values for the mixer and separation facilities.
