### ISSUE TITLE
remove calculated supply/capacity lines in the algorithm performance test 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#181]

**Comment by robfairh** [comment]
'd3ploy/tester.py' and 'd3ploy/plotter.py' will have added an option to plot those variables or not.

This will also be useful to plot the results of input files that don't use d3ploy.

**Comment by gwenchee** [comment]
The option to include or not include the calculated lines is implemented in https://github.com/arfc/d3ploy/pull/223

**Comment by robfairh** [comment]
Closed by #223
