### ISSUE TITLE
performance_tests tables titles and ylabels

### ISSUE THREAD

**Issue by robfairh** [arfc/d3ploy#190]
Titles of the plots should reflect the calculation method chosen.

ylabel should have the right units. For every commodity says "Mass(Kg)"
![input2_power](https://user-images.githubusercontent.com/43791150/52821746-5eb8ff80-3075-11e9-8a5d-ea657080fe1b.png)
![input2_sourceout](https://user-images.githubusercontent.com/43791150/52821751-6082c300-3075-11e9-8072-265f3a211ac6.png)

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/d3ploy/pull/201
