### ISSUE TITLE
Notion of 'under supply' for supply driven deployed facilities, also plots incomplete.

### ISSUE THREAD

**Issue by robfairh** [arfc/d3ploy#195]
Facilities that are deployed based on the supply they receive have values of under supply that are not consistent with the plots.

![case6_ma_reactorout](https://user-images.githubusercontent.com/43791150/53582954-2ec62d80-3b46-11e9-901a-5856c345027f.png)

![sepuedeborrar1](https://user-images.githubusercontent.com/43791150/53583141-941a1e80-3b46-11e9-939a-4f2d244e1257.png)

The function 'supply_under_demand' called from the function 'metrics' in 'tester.py' produces those values.

![image](https://user-images.githubusercontent.com/43791150/53583271-d9d6e700-3b46-11e9-92a2-69b9f7405a4f.png)

This issue can be closed when the values of 'commod'_undersupply are consistent with the plots.

**Comment by robfairh** [comment]
calc_demand and calc_supply don't appear completely in the plots.

![borrar2](https://user-images.githubusercontent.com/43791150/53590185-d4819880-3b56-11e9-9cea-46d0758a173f.png)

**Comment by gwenchee** [comment]
u circle the value 13? Should it be 0?

**Comment by robfairh** [comment]
I think it should be 1, not sure ... maybe 0.

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/d3ploy/pull/226
