### ISSUE TITLE
circle ci build issues 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#218]
I merged https://github.com/arfc/d3ploy/pull/217, and updated https://github.com/arfc/d3ploy/pull/213 to trigger the circle ci, however the tests are still not passing. I saw that you (@FlanFlanagan ) tried
 ```
pip uninstall h5py 
pip install --no-cache-dir h5py
``` 
in the docker file. Should we try this (https://stackoverflow.com/questions/48965309/h5py-import-error-on-libhdf5-serial-so-100)? 
```
sudo apt-get update
sudo apt-get install libhdf5-dev
sudo apt-get update
sudo apt-get install libhdf5-serial-dev
```

**Comment by FlanFlanagan** [comment]
Fixed with merger of #267
