### ISSUE TITLE
Extra Supply for each commodity 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#224]
The issue can be closed when the capability of providing user-defined extra supply for each commodity is added to d3ploy. The "extra supply" can be input as a percentage of total supply of that commodity.

**Comment by FlanFlanagan** [comment]
So the best way to do this is to artificial demand for a commodity. 

When d3ploy calculates the demand for a commodity we need to store that as the actual demand and then artificially bump it up for the testing demand. This will ensure that there is a capacity buffer for situations in which reactors are out for refuel, etc.

**Comment by FlanFlanagan** [comment]
Tackled in #232

**Comment by gwenchee** [comment]
This must also be implemented for the SupplyDrivenDeploymentInst to provide a capacity buffer

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/d3ploy/pull/233
