### ISSUE TITLE
allow each commodity to use a different prediction method 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#225]

**Comment by FlanFlanagan** [comment]
This can already be done using multiple institutions. Do we want this done within the same inst. Shouldn't be too difficult, but do we need it?

**Comment by gwenchee** [comment]
Oh yes, I forgot about that conversation. I was hoping to let the driving commod use a NO solver method (like ma) and the non-driving commodities to use a ML solver (like fft). So I will use two different institutions.
