### ISSUE TITLE
Driving commodity 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#23]
The demand driving commodity (the one governed by demand equation - growth rate and initial demand) is currently hard-coded as power. The user should be able to decide the demand-driving commodity.

This issue can be closed when the hard-coded demand-driving commodity is changed to a user input.

**Comment by FlanFlanagan** [comment]
This seems like an acceptable approach, but this is not a bug. It's an enhancement. 

We'll need a new input to indicate which commodity is the driving commodity. Which I think should default to power.

**Comment by gwenchee** [comment]
Yup that makes sense.

**Comment by gwenchee** [comment]
closed with https://github.com/ergs/d3ploy/pull/47 and https://github.com/ergs/d3ploy/pull/40
