### ISSUE TITLE
Add back lines for plots in 'plotter.py'

### ISSUE THREAD

**Issue by robfairh** [arfc/d3ploy#235]
For a small duration the plot is clearer with the symbols '+' and 'x' for supply and demand.
When the duration becomes larger, as it is the case for the transitions scenarios, it becomes quite confusing.
![image](https://user-images.githubusercontent.com/43791150/56612904-1e2cb380-65db-11e9-8dff-0bc6dbf496a0.png)

The issue can be closed when plotter.py recovers the capability of plotting with lines.

**Comment by gwenchee** [comment]
I think we can just make X and + smaller so that it looks like dots. So maybe an input for cross sizes

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/d3ploy/pull/236
