### ISSUE TITLE
supply data points in time step 1 and 2 are not showing 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#238]
The supply data points in time step 1 and 2 are not showing for the power plot and the supply data points in time step 2 is not showing for the fuel plot. 
![scenario_2_input_ma_fuel](https://user-images.githubusercontent.com/29397884/56631822-88b21380-661c-11e9-807c-9b5e98c229ad.png)
![scenario_2_input_ma_power](https://user-images.githubusercontent.com/29397884/56631823-88b21380-661c-11e9-8bbd-8eb09ad415ff.png)

**Comment by robfairh** [comment]
closed by #239
