### ISSUE TITLE
cyclus agentexit output table? 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#249]
When running a cyclus simulation, is a `agentexit` table expected? In `tester.py`'s `get_agent_dict` (https://github.com/arfc/d3ploy/blob/ecd876416a8736bf6e36d1fad45e9579f22595c8/d3ploy/tester.py#L375) there is notion of an `agentexit` table but I do not see its existence in the output sqlite file

**Comment by gwenchee** [comment]
Does anyone know whether we expect an agentexit table

**Comment by robfairh** [comment]
This is from one of the transition scenarios. The exit times correspond to the times where the reactors are decommissioned.

![image](https://user-images.githubusercontent.com/43791150/57002939-a33e3c80-6b88-11e9-9b22-588232644cb7.png)

**Comment by gwenchee** [comment]
Hm, i am having an issue of when i run a simulation that has reactors with finite lifetimes, there isn't an agentexit table. I will add my xml and sqlite here.

**Comment by robfairh** [comment]
For the case of the transition scenarios, the lwr's are deployed using deploy_inst. Would that have something to do with the table?

**Comment by gwenchee** [comment]
I did the same thing, i used deploy inst to deploy a bunch of reactors

**Comment by robfairh** [comment]
what branch are you working on?

**Comment by gwenchee** [comment]
This is my input file: https://github.com/gwenchee/d3ploy/blob/demoz/input/constant_transition.xml

**Comment by gwenchee** [comment]
It should run with the master branch.

**Comment by gwenchee** [comment]
Let me know if you notice anything funky

**Comment by robfairh** [comment]
I do not see anything weird from a first look. I ran it and the sqlite does not produce that table.

**Comment by gwenchee** [comment]
Yeah i'm very confused to why it is not producing that table.

**Comment by robfairh** [comment]
I added the deployment of the sink and now it shows the table. I have no idea why ....

![image](https://user-images.githubusercontent.com/43791150/57003877-793c4880-6b8f-11e9-9ee4-55109ed6295b.png)

This is the new xml file
https://github.com/robfairh/d3ploy/blob/gwen_deco/demonstrations/gwen_test.xml

**Comment by gwenchee** [comment]
lol weird, thanks!! :D

**Comment by robfairh** [comment]
Is it maybe that you need to empty the reactors to decommission them?

**Comment by gwenchee** [comment]
But you did not change anything with the reactors and they appear to be decommissioning? So it can't be that

**Comment by robfairh** [comment]
I just added the deployment of a sink. Nothing else. I think it makes sense, that the reactors need to exchange with some facility their spent fuel in order to be decommissioned. As in your xml there isn't a sink, the reactors keep the spent fuel and are not decommissioned (even though they stop producing power). I am not sure though.

**Comment by gwenchee** [comment]
Oh that makes sense. you are right, thanks @robfairh !
