### ISSUE TITLE
combine demand driven inst and supply driven inst 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#254]
Instead of having 2 institutions for demand driven and supply driven, there should be a toggle in one institution that switches between demand driven and supply driven.

**Comment by katyhuff** [comment]
Sounds good. Keep in mind: https://docs.python.org/2/tutorial/classes.html#multiple-inheritance

**Comment by gwenchee** [comment]
This is difficult to implement because there are separate functionalities that are implemented in both

**Comment by gwenchee** [comment]
It is difficult to implement, implementing this does not affect the capability of the d3ploy code. It just makes it neater.
