### ISSUE TITLE
D3ploy can't divide the production of power into different types of reactors.

### ISSUE THREAD

**Issue by robfairh** [arfc/d3ploy#255]
When the demand of power should be met by two types of reactors, for ex: 40% by MOX lwr's and 60% FR's, d3ploy won't do it. It will deploy reactors to meet the demand equation without considering the percentages. There isn't a way to define those percentages or to limit the number of facilities deployed.

In d3ploy the definition of two types of reactors is like this:
![image](https://user-images.githubusercontent.com/43791150/57954819-a68c3480-78b9-11e9-98fb-2f7978540662.png)

A way to solve this would be using the preferences and modify the lifetime of the previous reactors accordingly:
![image](https://user-images.githubusercontent.com/43791150/57954854-c6235d00-78b9-11e9-8d6a-a1ce7e54f7d2.png)

![image](https://user-images.githubusercontent.com/43791150/57954892-dfc4a480-78b9-11e9-9c6d-939a7c80b7ea.png)

This solution deploys first fr's and then mox's. D3ploy should be able to deploy both reactors at the same time and the user should be able to define the percentages of power that d3ploy should meet.

**Comment by gwenchee** [comment]
@robfairh Could you describe how this sharing capability works here? 
With respect to constraint, preferences etc. Like what happens first?

**Comment by robfairh** [comment]
It checks first if there are preferences greater than 0. If there are, it checks if they are equal. If they are different, then it deploys the one with the highest preference. If they are equal, it checks if they have a sharing preference. If it does, then it deploys based on that. If it doesn't it deploys the min number of facilities.

**Comment by robfairh** [comment]
closed by #279
