### ISSUE TITLE
D3ploy doesn't record the capacity of the mixer when it has multiple inputs for a commodity

### ISSUE THREAD

**Issue by robfairh** [arfc/d3ploy#257]
For the case where the mixer has only one input for a commodity (in this case Pu):

![image](https://user-images.githubusercontent.com/43791150/58037531-3e289780-7af3-11e9-9e25-d33e1da048fc.png)

The table timeseriescaclc_capacitylwrpu is the following:

![image](https://user-images.githubusercontent.com/43791150/58037513-32d56c00-7af3-11e9-9994-ccf599b068da.png)

When the mixer takes more than one input for the Pu:

![image](https://user-images.githubusercontent.com/43791150/58037600-5bf5fc80-7af3-11e9-9e02-0094c52b8caa.png)

The table timeseriescalc_capacitylwrpu becomes 0 at all timesteps:

![image](https://user-images.githubusercontent.com/43791150/58037705-a24b5b80-7af3-11e9-9465-b834f4b38b38.png)

The obvious consequence of this is that d3ploy sees that the capacity is 0 and deploys a new mixer everytime there is lwrpu available from the reprocesing facility.

**Comment by gwenchee** [comment]
can you show me the input xml for the d3ploy institution section of the input file?

**Comment by robfairh** [comment]
This is it for both input files:

![image](https://user-images.githubusercontent.com/43791150/58052647-02a1c380-7b1b-11e9-933b-deceb11018e9.png)

**Comment by robfairh** [comment]
The input files are here:
https://github.com/robfairh/transition-scenarios/tree/experimental3/input/eg01-eg29

- eg01-eg29-flatpower-d3ploy6.xml is the one that doesn't display anything in the table
- eg01-eg29-flatpower-d3ploy7.xml displays the table

**Comment by gwenchee** [comment]
It’s not obvious to me what is the issue. Maybe you need to do some debugging in the source code?

**Comment by gwenchee** [comment]
Let's go into the code and do some debugging @robfairh

**Comment by robfairh** [comment]
I run this file

https://github.com/robfairh/transition-scenarios/blob/experimental5/input/eg01-eg29/eg01-eg29-flatpower-nond3ploy.xml

And even though it doesn't use d3ploy, it doesn't have the tables timeserieddemandlwrpu and timeseriesdemandmoxpu:

![image](https://user-images.githubusercontent.com/43791150/61127383-bf0d6b00-a474-11e9-92ad-157cfe7b4461.png)

So @FlanFlanagan  was right, the issue is something in cycamore and the way the tables are recorded.

Even though having those tables makes life easier, I am not sure they are needed by d3ploy to deploy the right thing. This continues on my next comment.

**Comment by robfairh** [comment]
To make things simpler I made the following inputs:

1) nond3ploy-simple.xml:
https://github.com/robfairh/transition-scenarios/blob/experimental6/input/eg01-eg29/nond3ploy-simple.xml

2) d3ploy-simple1.xml
https://github.com/robfairh/transition-scenarios/blob/experimental6/input/eg01-eg29/d3ploy-simple1.xml

3) d3ploy-simple2.xml
https://github.com/robfairh/transition-scenarios/blob/experimental6/input/eg01-eg29/d3ploy-simple1.xml

4) d3ploy-simple3.xml
https://github.com/robfairh/transition-scenarios/blob/experimental6/input/eg01-eg29/d3ploy-simple3.xml

1)Doesn't use d3ploy, it's just the nond3ploy version, I deployed everything manually.
2)Not very important, but it just deploys sinks to see that d3ploy works with the input.
These two work fine.
3)the mixer is deployed using d3ploy. The table timeseriescalc_capacitylwrpu is 0 at all times. This causes the simulation to deploy new mixing facilities at all times. For this case, the mixer has two inputs for Pu lwrpu and frpu.

![image](https://user-images.githubusercontent.com/43791150/61132864-d7d04d80-a481-11e9-88e2-55eae839b2f7.png)

![image](https://user-images.githubusercontent.com/43791150/61133029-3b5a7b00-a482-11e9-91ec-45ba996f8f84.png)

4)the mixer is still deployed using d3ploy. This time, the mixer has only one input for Pu, lwrpu. This time calc_capacitylwrpu is 3000. And it deploys only one mixer. Of course this transition doesn't work because it won't use frpu, but the case helps to show what d3ploy is doing.

![image](https://user-images.githubusercontent.com/43791150/61132882-e61e6980-a481-11e9-8aa6-553a1ec74da5.png)

![image](https://user-images.githubusercontent.com/43791150/61133063-4b725a80-a482-11e9-9598-098746f1c504.png)

**Comment by robfairh** [comment]
It works well when I used the feature "installed_capacity" (thanks, @gwenchee),
now the issue could be closed when the predicted capacity feature works as well.

**Comment by robfairh** [comment]
Using installed capacity still has issues with the full input:

https://github.com/robfairh/transition-scenarios/blob/experimental6/input/eg01-eg29/eg01-eg29-flatpower-d3ploy4.xml

The capacity of the frmixer is 13e3 and the capacity of the moxmixer is 8e3. The supply of Pu is 20.8e3 then it deploys 1 frmixe and 1 moxmixer. The capacity should be 21e3, but the table shows just 8e3. Then on the next time step where there is a supply of Pu, it deploys 2 more moxmixer, the table shows a capacity for lwrpu of 24e3. The table is just recording the capacity of one of the prototypes (moxmixer) deployed by d3ploy. Both frmixer and moxmixer are supply driven deployed by the same commodity: lwrpu.

**Comment by robfairh** [comment]
In the beginning it wasn't clear what the issue was. After looking into it, we found that this issue can be decoupled into 3 smaller issues. This issue is closed, and the 3 issues are open. These are #270, #273, #274.
