### ISSUE TITLE
D3ploy fails to record the capacity of mixers when they are deployed using the same commodity.

### ISSUE THREAD

**Issue by robfairh** [arfc/d3ploy#274]
I was trying to run the following input:

https://github.com/robfairh/transition-scenarios/blob/experimental6/input/eg01-eg29/eg01-eg29-flatpower-d3ploy4.xml

Using the installed capacity feature, D3ploy deploys frmixer and moxmixer based on the supply of lwrpu:

```
        <SupplyDrivenDeploymentInst>
        <calc_method>ma</calc_method>
        <installed_cap>1</installed_cap>
        <facility_commod>
        <item>
            <facility>frmixer</facility>
            <commod>lwrpu</commod>
        </item>
        <item>
            <facility>moxmixer</facility>
            <commod>lwrpu</commod>
        </item>
        </facility_commod>
        <facility_capacity>
        <item>
            <facility>moxreprocessing</facility>
            <capacity>1e8</capacity>
        </item>
        <item>
            <facility>frmixer</facility>
            <capacity>1.3e4</capacity>
        </item>
        </facility_capacity>
```

A frmixer and a moxmixer are deployed, but only the capacity of the moxmixer is recorded:

![image](https://user-images.githubusercontent.com/43791150/61215262-f3c92e80-a6cf-11e9-9336-d3fc9e5be280.png)

![image](https://user-images.githubusercontent.com/43791150/61214658-19edcf00-a6ce-11e9-93cb-5d7f337d2dae.png)

The issue can be closed when d3ploy records the capacity of all the deployed mixers.

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/d3ploy/pull/275
