### ISSUE TITLE
D3ploy Doesn't Work

### ISSUE THREAD

**Issue by kipk49** [arfc/d3ploy#278]
Cloned d3ploy from Gwen's repository (have tried ARFC's and Roberto's on separate Ubuntu installs) on a fresh Ubuntu installation, used pip3 to install required dependencies as provided in the README documentation.

Attempted to run (GitHub won't post XML, so it's in txt format): 
[d3ploytest.txt](https://github.com/arfc/d3ploy/files/3407312/d3ploytest.txt)

I receive the following error: `ERROR(core  ):No module found for path libd3ploy.demand_driven_deployment_inst.so`

I've tried modifying it in various ways, it seems that mentioning the `demand_driven_deployment_inst` in the Archetypes section is enough to cause the module error to show up.

On a side note, `pytest` fails with the following error:
[largeannoyingerror.txt](https://github.com/arfc/d3ploy/files/3407327/largeannoyingerror.txt)

All the of the individual failures seem to be caused by the same module path error from above.

Thoughts?

Edit: Added missing info

**Comment by FlanFlanagan** [comment]
@kipk49 you should not be using Gwen's repo. You should use the ARFC one. 

So this error suggests that d3ploy isn't building properly. This makes me think one of the dependencies is not installed correctly. 

Which version of numpy are you running?

**Comment by kipk49** [comment]
Oops, forgot to mention that: this is my third attempted d3ploy installation. 1st try used ARFC repo, 2nd used Roberto's, 3rd uses Gwen's. They all throw the same error codes, but Sonata got Gwen's version to work on her laptop somehow.

I believe I currently have multiple numpy versions installed; when I used pip3 to install dependencies, one or two of them installed additional numpy versions alongside themselves.
`numpy.__version__` yields 1.14.3, and I haven't uninstalled other versions yet.

**Comment by FlanFlanagan** [comment]
Hmm,

and you have arima, statsmodels, and arch?

Are you using any conda environments?

**Comment by kipk49** [comment]
I have pmdarima, statsmodels, and arch in whichever versions pip3 defaulted to.

I think I'm using the base environment that Anaconda3 initialized when first installed, see `(base) kip@kip-arfc:~$`

**Comment by FlanFlanagan** [comment]
Okay, my last thought is that one of the imports is failing 

Can you check all the inputs in the solvers.py, and the inst.py files? I know it's frustrating, sorry

**Comment by kipk49** [comment]
OK; per Roberto's suggestion I made a python script that attempts to import everything used by any of the solvers.py or the inst.py, shown in txt format because GitHub is wack:
[importtests.txt](https://github.com/arfc/d3ploy/files/3407551/importtests.txt)

When I run it I get `Traceback (most recent call last):
  File "importtests.py", line 13, in <module>
    import d3ploy.NO_solvers as no
  File "/home/kip/anaconda3/lib/python3.6/site-packages/d3ploy/NO_solvers.py", line 10, in <module>
    from arch import arch_model
ModuleNotFoundError: No module named 'arch'`

However, if I do `pip3 show arch` it says I have 4.8.1 installed

**Comment by FlanFlanagan** [comment]
Interesting. Pip install should work for arch. 

Do you know which python is your default python?

**Comment by kipk49** [comment]
Anaconda3's site indicated 3.7, however `python` says default is 3.6.7 from conda-forge

**Comment by FlanFlanagan** [comment]
I wonder if python isn't catching the pip install because it's from conda? Did you try 

conda install -c bashtage arch

**Comment by kipk49** [comment]
Did `conda install -c bashtage arch`, was told it successfully installed.

Reran `setup.py install`, still the same module error

**Comment by katyhuff** [comment]
Update from the call. An inconsistent python environment was (probably) at fault.

Consider: 
- updating from ubuntu 16.04 to 18.04
- installing anaconda on a fresh ubuntu
- setting PATH and PYTHONPATH carefully in your environment
- using only conda or pip for your python related stuff (never apt-get)
- using conda environments to keep your life cleaner. https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html 
- using "echo" "which" "env" and "<executible> --version" to double check that you're using the executibles you intend to use.

**Comment by kipk49** [comment]
OK, here's what I did:

- fresh install of Ubuntu, immediately auto-upgraded to 18.04.02 LTS.
- attempted to run Greg's script for Git, Jupyter Notebook, and Sublime, but it broke and did nothing
- manually installed and set up Git
- downloaded and bashed latest .sh script from Anaconda3
- `echo 'export PATH="~/anaconda/bin:$PATH"' >> ~/.bashrc`
- `source .bashrc`
- `conda config --add channels conda-forge`
- `conda install -y openssh gxx_linux-64 gcc_linux-64 cmake make docker-pycreds git xo python-json-logger python=3.6 glibmm glib=2.56 libxml2 libxmlpp libblas libcblas liblapack pkg-config coincbc=2.9 boost-cpp hdf5 sqlite pcre gettext bzip2 xz setuptools nose pytables pandas jinja2 cython==0.26 websockets pprintpp`
- cloned and installed Cyclus without issue
- cloned and installed Cycamore without issue
- cloned my tests repo to test Cyclus functionality, runs fine
- used Conda to install pip, then used pip to install the 3 d3ploy dependencies
- cloned d3ploy and ran `setup.py install`
- ran `pytest` for d3ploy, same 22 failures as earlier
- used Conda to install numpy 1.16.4

Now whenever I do `cyclus` I get:`cyclus: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory`

Haven't tried anything with PATH, PYTHONPATH, or environments yet, but the `which pip` and `which python` commands seem to show locations that are in good order.

Here is the result of `history`: 
[history.txt](https://github.com/arfc/d3ploy/files/3412467/history.txt)

**Comment by kipk49** [comment]
Appears to be running now, I did the following after the steps listed above:
- installed `libopenblas` using Conda
- ran `install.py --clean-build` for both Cyclus and Cycamore
