### ISSUE TITLE
update config.yml file to include all the new tests

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#280]
This issue can be closed when all the new integration tests are added to the config.yml file (https://github.com/arfc/d3ploy/blob/a6a93e0bf45c79c036560690d3525c3ce982510c/.circleci/config.yml#L60) so that they are ran in the CI

**Comment by gwenchee** [comment]
Could u do this @robfairh

**Comment by robfairh** [comment]
close with #283

**Comment by robfairh** [comment]
It is missing the last test "share_test" that will be in #279

**Comment by robfairh** [comment]
closed by #283 and #279
