### ISSUE TITLE
Some of the prediction methods don't have the capability to look forward.

### ISSUE THREAD

**Issue by robfairh** [arfc/d3ploy#287]
The DO and the SO methods don't have the look forward capability. This methods don't use "steps".

This issue can be close when this capability is added to these methods. Either that or take the decision of ignoring this capability.

**Comment by robfairh** [comment]
#288 addresses partially this issue.
see #288 for more details.

**Comment by gwenchee** [comment]
I think it's fine if we can't add the capability to those methods. We can still include them in the sensitivity analysis but just include data for 1 back step and we can explain that this is a constraint with these methods

**Comment by gwenchee** [comment]
So let's close the issue.
