### ISSUE TITLE
Installed cap should't be used with the back end

### ISSUE THREAD

**Issue by robfairh** [arfc/d3ploy#289]
When using installed cap for the back end of the cycle, the simulations fail.
This is caused by the fact that calc_capacity takes the values of the capacity of the facilities. D3ploy doesn't see that the capacity of these facilities change as they get full.

The next input file shows that (change the extension to .xml to run it):
[simple.txt](https://github.com/arfc/d3ploy/files/3488081/simple.txt)

The reactor produce 1e3 of waste every 2 timesteps. The sink can take up to 1e4. After 20 timesteps, the sink should get full, then d3ploy should be deploying a new one, but it doesn't.

- timeseriessupplylwrout:
![image](https://user-images.githubusercontent.com/43791150/62809896-e7af7180-bac1-11e9-8486-cdaf732f715f.png)

- timeseriesdemandlwrout:
![image](https://user-images.githubusercontent.com/43791150/62809919-f433ca00-bac1-11e9-9ce5-0c09ac1c6f03.png)

- timeseriescalc_capacitylwrout:
![image](https://user-images.githubusercontent.com/43791150/62809972-19c0d380-bac2-11e9-80a1-066d4f1e48ff.png)

I think we should enable the possibility of using installed cap in the supply driven deployment, because it will cause the simulations to fail. Then, the issue can be closed when those changes have taken place.

**Comment by robfairh** [comment]
What do you think @gwenchee ?

**Comment by robfairh** [comment]
@gwenchee do you think we can close this issue?

**Comment by gwenchee** [comment]
Yup. We shouldn't use installed capacity for the back end because it will cause no new facilities to deploy when there is a shortage of space in the back buffer since it is deploying based on installed capacity. 

However, we are leaving the installed capacity capability in `supply_driven_inst`.
