### ISSUE TITLE
NO_Inst reactor not building 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#48]
`NO_Inst` does not built facilities when demand eq is a constant value

**Comment by gwenchee** [comment]
link to XML file: https://gist.github.com/gwenchee/67d85b1445a4dac383d92ab486bfd59b
This version of d3ploy is in gwenchee, branch: deploy_logic_fix

**Comment by FlanFlanagan** [comment]
Interesting. Thanks, I'll look into this

**Comment by gwenchee** [comment]
closed with https://github.com/ergs/d3ploy/pull/53
