### ISSUE TITLE
addlibrecordtimeseries

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#69]
addlibrecordtimeseries for the calculated supply and demand for each commodity 

include the institution ID so we don't double count

**Comment by gwenchee** [comment]
@FlanFlanagan for this issue, would it just be adding `lib.TIME_SERIES_LISTENERS["demand"+commod].append(self.extract_demand)` to enternotify but for calculated supply and demand. And making corresponding `extract_demand` and `extract_supply`functions for the calculated supply and demand?

**Comment by FlanFlanagan** [comment]
I think it would be lib.TIME_SERIES_LISTENERS[agentID()+"demand"+commod]

**Comment by gwenchee** [comment]
closed with https://github.com/ergs/d3ploy/pull/75
