### ISSUE TITLE
Demand equation variability

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#8]
Currently the demand equation is given by the equation
`initial_demand * ((1 + growth_rate)**time)`.

However, it would be nice if more options are provided, like the piecewise functions
available in `cycamore::Growthregion`.

**Comment by FlanFlanagan** [comment]
I agree with this. A piece wise is a good choice as well. 

+1

**Comment by gwenchee** [comment]
This issue is moved to https://github.com/ergs/d3ploy/issues/20.
