### ISSUE TITLE
Random prototype selection

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#9]
Currently, d3ploy finds a random prototype among the lists of prototypes in the input parameter,
and calculates the prod_rate by dividing the supply by the number of children of the institute.
( Or in the most recent release this is not the case)

Maybe it would be more beneficial to simply have one prototype (vector prototypes -> str prototype)
and calculate the prod_rate by doing `supply / len(self.children)`.

Any thoughts on this @FlanFlanagan ?

**Comment by FlanFlanagan** [comment]
This can definitely be improved. We store a prototype -> production rate data map. should probably just switch to that.

**Comment by gwenchee** [comment]
This issue is solved by solving this new issue: https://github.com/ergs/d3ploy/issues/18
