### ISSUE TITLE
processing capacity demand 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#95]
@jbae11 ?

**Comment by jbae11** [comment]
The discussion was that we currently have direct mass demands and supply recorded in the timeserieslibrecord.

However, this does not necessarily translate to the material processing capacity demand. As a simple example, if we had a fuel cycle such as:
```
POWER <- reactor <- FUEL <- enrichment <- NATU <- source
```
we don't know the amount of SWU demand given the FUEL demand. Moreover, we don't know the NATU demand given this FUEL demand...?

**Comment by FlanFlanagan** [comment]
This is not an issue of d3ploy. This issue relies elsewhere. I'll shift the issue to there.
